apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
  namespace: default  # Substitua com o namespace correto, caso necessário
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp  # Nome do Deployment que será escalado
  minReplicas: 1  # Mínimo de réplicas
  maxReplicas: 5  # Máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # A média de utilização de CPU desejada (em %)
